server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://gu.lhqs1314.cn:3306/temp
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
   map-underscore-to-camel-case: true #开启驼峰映射